name: iforestASD
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip=23.3.1
  - pip:
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - pyod==2.0.5
      - combo==0.1.3
      - dash==3.0.4
      - plotly==6.1.2
      - dash-bootstrap-components==1.6.0
      - pyyaml==6.0.2
      - gunicorn==23.0.0
      - flask==3.0.2
      - requests==2.31.0
      - pysad==0.3.4

  
